version: '3.9'
services:
  zookeeper:
    image: 'bitnami/zookeeper:3.6'
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
  kafka:
    build:
      context: ./docker/kafka
      dockerfile: Dockerfile
    environment:
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_LISTENERS=PLAINTEXT://:9092
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092
    ports:
      - '9092:9092'
    depends_on:
      - zookeeper
  redis:
    build:
      context: ./docker/redis
      dockerfile: Dockerfile
    ports:
      - '6379:6379'